In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))
a=np.array(42)
print(a)
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b[0,1,2])
print(arr[-1])
print(arr[2]+arr[3])
c=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(c.reshape(2,3,2))
for x in c:
    print(x)
d=np.array([[1,2,3,4],[5,6,7,8]])
print(d.shape)
print(arr.dtype)
e=np.array(['divi','kishore','sai'])
print(e.dtype)
print(c[1:5])

[1 2 3 4]
<class 'numpy.ndarray'>
42
6
4
7
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12
(2, 4)
int32
<U7
[2 3 4 5]
