In [5]:
import numpy as np
print(np.__version__)
#print(np.show_config())

1.21.5


# add function 

In [6]:
#print(np.info(np.add))

# none of the elements of a given array is zero

In [7]:
x=np.array([1,2,3,4])
print("Original array:")
print(x)
print("test if none of the elements of the said is zero:")
print(np.any(x))
x=np.array([0,1,2,3])
print("Original array:")
print(x)
print("test if none of the elements of the said is zero:")
print(np.any(x))

Original array:
[1 2 3 4]
test if none of the elements of the said is zero:
True
Original array:
[0 1 2 3]
test if none of the elements of the said is zero:
True


# To test whether any of the the given array is non-zero

In [10]:
x=np.array([1,0,0,0])
print("Original array:")
print(x)
print(np.any(x))
y=np.array([0,0,0,0])
print(np.any(y))

Original array:
[1 0 0 0]
True
False


# to test a given  array element  elemnet-wise  for finiteness or Infintiteness or null value

In [12]:
a=np.array([1,0,np.nan,np.inf])
print(a)
print(np.isfinite(a))

[ 1.  0. nan inf]
[ True  True False False]


In [14]:
print(np.isinf(a))

[False False False  True]


In [15]:
print(np.isnan(a))

[False False  True False]


# To test element-wise for complex number and real number and scalar or not

In [18]:
a=np.array([1+1j,1+0j,4.5,3.2,2j])
print("Originala array:")
print(a)
print("checking for complex number:")
print(np.iscomplex(a))
print("checking for real number:")
print(np.isreal(a))
print("Checking for scalr type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1]))

Originala array:
[1. +1.j 1. +0.j 4.5+0.j 3.2+0.j 0. +2.j]
checking for complex number:
[ True False False False  True]
checking for real number:
[False  True  True  True False]
Checking for scalr type:
True
False


# to create an element  wise comparision(greater,greater_equal,less,less_equal of given 2 arrays

In [21]:
x=np.array([3,5])
y=np.array([2,5])
print("Original array:")
print(x)
print(y)
print("Comaparsion_grater")
print(np.greater(x,y))
print("Comparison_grater_equal")
print(np.greater_equal(x,y))
print("Comparision less")
print(np.less(x,y))
print("comparision less equal")
print(np.less_equal(x,y))

Original array:
[3 5]
[2 5]
Comaparsion_grater
[ True False]
Comparison_grater_equal
[ True  True]
Comparision less
[False False]
comparision less equal
[False  True]


# to create an element-wise comparision (equal,equal within a tolerance of given two given arrays

In [22]:
x=np.array([72,79,85,90,150,-135,120,10,60,100])
y=np.array([72,79,85,90,150,-135,120,10,60,100.00001])
print("Original array:")
print(x)
print(y)
print("comparision equal:")
print(np.equal(x,y))
print("Comparision equal within a tolerance:")
print(np.allclose(x,y))

Original array:
[  72   79   85   90  150 -135  120   10   60  100]
[  72.        79.        85.        90.       150.      -135.
  120.        10.        60.       100.00001]
comparision equal:
[ True  True  True  True  True  True  True  True  True False]
Comparision equal within a tolerance:
True


# To create an array with the values 1,7,13,105 and determine the size of the memory occupied by the array

In [27]:
x=np.array([1,7,13,105,8798])
print("Original array:")
print(x)
print("Size of the memory occupied by the memory:")
print("%d bytes"%(x.size*x.itemsize))

Original array:
[   1    7   13  105 8798]
Size of the memory occupied by the memory:
20 bytes
